# Generated by Django 4.1 on 2022-09-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Фото')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[(None, 'Выберите категорию'), ('1', 'Россия'), ('2', 'Мир'), ('3', 'Бывший СССР'), ('4', 'Экономика'), ('5', 'Силовые структуры'), ('6', 'Наука и техника'), ('7', 'Культура'), ('8', 'Спорт'), ('9', 'Интернет и СМИ'), ('10', 'Ценности'), ('11', 'Путешествия'), ('12', 'Из жизни')], max_length=2)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
