# Generated by Django 4.1 on 2022-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Россия'), ('2', 'Мир'), ('3', 'Бывший СССР'), ('4', 'Экономика'), ('5', 'Силовые структуры'), ('6', 'Наука и техника'), ('7', 'Культура'), ('8', 'Спорт'), ('9', 'Интернет и СМИ'), ('10', 'Ценности'), ('11', 'Путешествия'), ('12', 'Из жизни'), ('13', 'Среда обитания'), ('14', 'Забота о себе')], default='1', max_length=2),
        ),
    ]
